### ISSUE TITLE
[Feature request] set multiple memcache(apc/mongo...) cache services in app/config.yml

### ISSUE THREAD

**Issue by pulzarraider** [sonata-project/SonataCacheBundle#10]
I would like to have two or more memcache cache services with different configurations (prefix, different servers) and I would like to set their own names.

The bundle configuration defined in app/config.yml must be changed to make this working.

**Comment by core23** [comment]
Can you provide a PR?

**Comment by core23** [comment]
This issue is very old. Feel free to reopen, if the error still exists. 

A PR would be welcome if you reopen this issue.
