### ISSUE TITLE
Bundle may not work dependeing on other bundles loading order

### ISSUE THREAD

**Issue by fbourigault** [sonata-project/SonataCacheBundle#166]
While using SonataCacheBundle in a Flex application, I get an error about missing `doctrine.connections`:
```
  [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]
  You have requested a non-existent parameter "doctrine.connections".


Exception trace:
 () at .../vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php:100
 Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get() at .../vendor/symfony/dependency-injection/ParameterBag/EnvPlaceholderParameterBag.php:56
 Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get() at .../vendor/symfony/dependency-injection/Container.php:146
 Symfony\Component\DependencyInjection\Container->getParameter() at .../vendor/sonata-project/cache-bundle/DependencyInjection/SonataCacheExtension.php:97
 Sonata\CacheBundle\DependencyInjection\SonataCacheExtension->configureORM() at .../vendor/sonata-project/cache-bundle/DependencyInjection/SonataCacheExtension.php:62
 Sonata\CacheBundle\DependencyInjection\SonataCacheExtension->load() at .../vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:66
 Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process() at .../vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php:39
 Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process() at .../vendor/symfony/dependency-injection/Compiler/Compiler.php:143
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at .../vendor/symfony/dependency-injection/ContainerBuilder.php:746
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at .../vendor/symfony/http-kernel/Kernel.php:575
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at .../vendor/symfony/http-kernel/Kernel.php:117
 Symfony\Component\HttpKernel\Kernel->boot() at .../vendor/symfony/framework-bundle/Console/Application.php:65
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at .../vendor/symfony/console/Application.php:125
 Symfony\Component\Console\Application->run() at .../bin/console:36
```

This occurs because the [SonataCacheExtension](https://github.com/sonata-project/SonataCacheBundle/blob/e1db36ce6fc9b37354706a3af77b6e811aee2f56/DependencyInjection/SonataCacheExtension.php#L93-L101) use a parameter registered by `DoctrineBundle`.

As we are adding the subscriber to every connection, I suggest to remove this code and add the `doctrine.event_subscriber` to the `sonata.cache.orm.event_subscriber` definition without the `connection` attribute.

Same change could be applied to the `sonata.cache.phpcr_odm.event_subscriber` definition.

If you agree with those changes, I will open a PR.

**Comment by greg0ire** [comment]
I'm on my phone so it's hard for me to figure out how you are going to keep the cache subscriber working if you remove that piece of information, because I don't know how it is used. Could you link to the relevant piece of code? Also that sounds like the kind of issue that could be solved with a compiler pass or a prependextensioninterface implementation.

**Comment by fbourigault** [comment]
When the `doctrine.event_subscriber` tag is provided without the `connection` attribute, the [`RegisterEventListenersAndSubscribersPass`](https://github.com/symfony/doctrine-bridge/blob/9be86cfba82efaa2a64b67a5e96395c71e57f982/DependencyInjection/CompilerPass/RegisterEventListenersAndSubscribersPass.php#L120) from the `symfony/doctrine-bridge` automatically loops through all configured connections. So we can simply remove our use of the `doctrine.connections` attribute and just add the `doctrine.event_subscriber` tag without the `connection` attribute.

**Comment by greg0ire** [comment]
Now I understand :) go for it!
