### ISSUE TITLE
[RFC] Using twig service with SonataCacheBundle

### ISSUE THREAD

**Issue by covex-nn** [sonata-project/SonataCacheBundle#206]
## Subject

To find Twig base template class, `Sonata\CacheBundle\SonataCacheBundle::boot` method gets `twig` service from container and does not check if it exists. See [SonataCacheBundle.php#L29](https://github.com/sonata-project/SonataCacheBundle/blob/2.x/src/SonataCacheBundle.php#L29)

## Steps to reproduce

Execute following commands:

```
composer create-project symfony/skeleton .
composer require sonata-project/cache-bundle
```

## Actual results

You will see a error message:

> !!
> !!  In Container.php line 270:
> !!
> !!    You have requested a non-existent service "twig".
> !!

---

The main goal of `SonataCacheBundle::boot` method  it to call `attachRecorder` method of a Twig base template class. This method exists only in `Sonata\CacheBundle\Twig\TwigTemplate13` and `Sonata\CacheBundle\Twig\TwigTemplate14` classes and these classes are removed in `master` branch.

To create a recipe for Flex, error with non-existent `twig` service must be fixed. How do you think what is the best solution: (1) to add `symfony/twig-bundle` to composer.json or (2) to add a "wrapper" `if ($this->container->has('twig`)) { ... }` in `SonataCacheBundle::boot` method?

And anyway boot method should be removed in master branch.

**Comment by jordisala1991** [comment]
Second seems better

**Comment by kunicmarko20** [comment]
Can it cache bundle work without twig? if yes, then an `if` is good, if no, then we need to add twig dependency. Do you have time to also create a PR on master to remove boot method?

**Comment by covex-nn** [comment]
@kunicmarko20 CacheBundle can work without `twig` service:

* There is no "twig" in code (only in comments and configuration)
* TwigTemplate13 and TwigTemplate14 are not compatible with `twig/twig: ^2.0`: these classes are overriding `getAttribute` method of [\Twig_Template](https://github.com/twigphp/Twig/blob/2.x/lib/Twig/Template.php) class, but it was removed, i guess. So it did not work anyway

I would create PR on master branch after merge my first PR in master to avoid conflicts. But i see, that you already created it (#208)

**Comment by kunicmarko20** [comment]
Ah, you weren't replying and I saw you were online so I thought you do not have time, sry. Does this mean you can now create recipe for this bundle?

**Comment by covex-nn** [comment]
I checked how bundle works without `twig` =)

Yes, it will be possible to create a recipe after release. May be there is some configuration, that can be used just with Symfony + PHP without APC? It there is no, then a recipe will contain commented lines from [2.1. Configuration](https://sonata-project.org/bundles/cache/2-x/doc/reference/installation.html#configuration) and [5.3. Configuration](https://sonata-project.org/bundles/cache/2-x/doc/reference/counter.html#configuration) and links to documentation, also it will contain routing configuration
