### ISSUE TITLE
Deprecate this bundle

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataCacheBundle#279]
## Feature Request

There is no need for the bundle anymore. Symfony / PSR cache is more common. Even doctrine dropped their custom cache.

**Comment by greg0ire** [comment]
Even doctrine dropped there custom cache.

> trying to, but not there yet I'm afraid :P

**Comment by VincentLanglet** [comment]
Let's start with the README https://github.com/sonata-project/SonataCacheBundle/pull/289

**Comment by core23** [comment]
@greg0ire @OskarStark can you do this?

**Comment by VincentLanglet** [comment]
I updated the devkit @core23 https://github.com/sonata-project/dev-kit/pull/617

**Comment by greg0ire** [comment]
Done

**Comment by greg0ire** [comment]
I'm wondering if it's not a bit premature… I mean we have lots of bundles relying on the cache bundle, shouldn't we move them to something else first?

**Comment by greg0ire** [comment]
It's not like the package is abandoned or triggering deprecations though :thinking: 
What do we mean exactly by deprecating? Asking because of https://github.com/sonata-project/dev-kit/pull/617
Will we refuse any PRs ? Should we stop getting improvements from dev-kit?

**Comment by VincentLanglet** [comment]
IMO, we're just deprecating the package. Which means we're not recommending the usage of it, and recommend to use something else instead.

When we're deprecating something in a bundle,
- First we trigger a deprecation message
- Second we're fixing the deprecation in others bundle
- Third we're removing it

Adding `[deprecated]` is like the step one.

**Comment by greg0ire** [comment]
> Should we stop getting improvements from dev-kit?

And this sounds like step 3

**Comment by VincentLanglet** [comment]
> > Should we stop getting improvements from dev-kit?
> 
> And this sounds like step 3

I don't really know what is doing the dev-kit.
@core23 Asked me a PR, so I copied the coreBundle one
https://github.com/sonata-project/dev-kit/commit/85390bb787bd8c173cff70d20fa7a8b6a7232488#diff-70800a36c38d85e21390f3af255c8420

And the "step 2" is still not finished for the core-bundle.

So if these PR shouldn't be made for Cache/Intl/EasyExtend in the devkit, it should not have been done for the CoreBundle too.

**Comment by greg0ire** [comment]
I guess this must be in order to avoid extra work when a dev-kit PR does not apply cleanly to one of these bundles. I will merge the cache PR and deploy, this is probably fine :crossed_fingers:

**Comment by core23** [comment]
We should also add a new `abandoned` entry to the `composer.json` file

**Comment by greg0ire** [comment]
Wouldn't this trigger warnings for people using our other packages, like the block bundle?

**Comment by core23** [comment]
That's right but okay. We deprecated the bundle on GitHub, so we should deprecate the bundle everywhere

**Comment by jordisala1991** [comment]
This issue should be closed and instead one on PageBundle might be opened to track the efforts of remove this deprecated bundle from there.
