### ISSUE TITLE
Support for Memcache extension for Windows Environment development's sake.

### ISSUE THREAD

**Issue by 4w3s3m0** [sonata-project/SonataCacheBundle#48]
Is there any hope that we could use memcache instead of memcached? The problem is  memcached dll is not yet available on windows.

**Comment by fbourigault** [comment]
IMHO, this could be closed as memcache is not compatible with PHP 7.0+ and "deprecated" in favor of memcached.

**Comment by greg0ire** [comment]
Thanks!
