### ISSUE TITLE
Symfony 2.7 BC break

### ISSUE THREAD

**Issue by gnutix** [sonata-project/SonataCacheBundle#72]
Because of https://github.com/symfony/TwigBundle/commit/a1d022df350e4cf8689287a09c661488955790d5, there is a BC break in this bundle : 

```
[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]  
  The parameter "twig.options" must be defined.
```

`SonataCacheBundle.php` tries to access `twig.options` parameter to get `base_template_class`. Unfortunately, it seems like there is no way to access this value with the current `TwigExtension` code.

Should an issue be opened on Symfony side ? Or should Sonata code be changed somehow ?

**Comment by richardfullmer** [comment]
Hit this today trying to upgrade since SF2.7 is now stable.

**Comment by rande** [comment]
Is ``base_template_class`` available in the container ?

**Comment by richardfullmer** [comment]
```
$ ./app/console debug:container --parameters |grep -i base_template_class
$
```

It is not.

**Comment by apfelbox** [comment]
Shouldn't `$this->get("twig")->getBaseTemplateClass()` work?

**Comment by manuonet** [comment]
i got the same problem with an upgrade from 2.3 to 2.7 today.
i dont' understand how to fix this?

**Comment by rande** [comment]
@apfelbox yep, can you create a PR ?

**Comment by manuonet** [comment]
Hi
is it possible that someone give us a explanation about this bug? 
Do you have some tips to debug or find some information?
i just upgraded from 2.3 to 2.7, with the change of composer.json file.

**Comment by linasm83** [comment]
Just a created a PR regarding this issue.

@manuonet the problem is not your config there, just as we a fix in this bundle code to work it on symfony 2.7

**Comment by manuonet** [comment]
OK thanks a lot! 
I always am questioning my work rather than the other ...

**Comment by bbelohorec** [comment]
FIX with composer.phar update sonata-project/cache-bundle
